# Generated by Django 3.1.2 on 2021-05-25 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='is_redeemed',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='redemptionDateTime',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='cart',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='TransactionHistoryArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('transactionDateTime', models.DateTimeField()),
                ('redemptionDateTime', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benefits.employeeuser')),
                ('buyerCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benefits.company')),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benefits.benefits')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benefits.benefitsprovidercompany')),
            ],
        ),
    ]
