# Generated by Django 3.1.2 on 2021-05-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0002_auto_20210525_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='benefits',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
