# Generated by Django 3.1.2 on 2021-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0004_auto_20210525_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefits',
            name='is_service',
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
