# Generated by Django 3.1.2 on 2021-05-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0005_auto_20210525_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='postalcode',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='postalcode',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
