# Generated by Django 3.1.2 on 2021-05-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0006_auto_20210525_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeuser',
            old_name='address',
            new_name='addressLineOne',
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='address',
            new_name='addressLineOne',
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='addressLineTwo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='addressLineTwo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
